name: Laravel CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, sqlite, pdo_sqlite, tokenizer, ctype, json
          coverage: none

      - name: Copy .env for testing
        run: |
          cp .env.example .env.test
          echo "APP_ENV=testing" >> .env.test
          echo "APP_DEBUG=true" >> .env.test
          echo "APP_KEY=base64:2ZMjV6NE1qUWlKSE5KY2pVdWFXTmpaR1kzWmprMk5qUT0=" >> .env.test
          echo "DB_CONNECTION=sqlite" >> .env.test
          echo "DB_DATABASE=:memory:" >> .env.test
          echo "CACHE_DRIVER=array" >> .env.test
          echo "SESSION_DRIVER=array" >> .env.test
          echo "QUEUE_CONNECTION=sync" >> .env.test
          echo "MAIL_MAILER=log" >> .env.test

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress

      - name: Generate key
        run: php artisan key:generate --env=test

      - name: Run migrations
        run: php artisan migrate --env=test --force

      - name: Run tests
        run: vendor/bin/phpunit --testdox --colors=always

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            tests/Feature/
            tests/Unit/
          retention-days: 5
